### ISSUE TITLE
支持 docker compose 方式部署

### ISSUE THREAD

**Issue by hoky** [kkangert/kspider#3]
这样简单易用，不需要自己去创建docker image。

**Comment by kkangert** [comment]
> 这样简单易用，不需要自己去创建docker image。

是否可以贡献一下这方面？

**Comment by kkangert** [comment]
https://kspider.kangert.top/BasicCourse/install.html
已提供，可以试试

**Comment by kkangert** [comment]
> https://kspider.kangert.top/BasicCourse/install.html
> 已提供，可以试试

存在一些问题待修复

**Comment by kkangert** [comment]
> > https://kspider.kangert.top/BasicCourse/install.html
> > 已提供，可以试试
> 
> 存在一些问题待修复

此问题已修复 [相关提交](https://github.com/kkangert/kspider-ui/commit/3f4487c3d99e07b360c41f3dd323ba459acc0b4f)
