### ISSUE TITLE
跑起来点登录出现接口路径找不到

### ISSUE THREAD

**Issue by xlsfs** [kkangert/kspider#6]
用
docker-compose -f deploy/kspider.yml up
跑起来后，
进入网址http://127.0.0.1/ 点登录出现接口路径找不到
POST http://127.0.0.1/api/auth/login 403 (Forbidden)

终端报错

`kspider           | 2024-07-19 04:01:00.918 ERROR 7 --- [0.0-8086-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
kspider           |
kspider           | org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
kspider           | 	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535)
kspider           | 	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505)
kspider           | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196)
kspider           | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
kspider           | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
kspider           | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kspider           | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
kspider           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kspider           | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
kspider           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kspider           | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
kspider           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kspider           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kspider           | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
kspider           | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
kspider           | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
kspider           | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
kspider           | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
kspider           | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
kspider           | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
kspider           | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
kspider           | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
kspider           | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
kspider           | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
kspider           | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
kspider           | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
kspider           | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
kspider           | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kspider           | 	at java.base/java.lang.Thread.run(Thread.java:833)
kspider           |`

**Comment by xlsfs** [comment]
数据库内kspider_user为空，手动添加一条kangert和111111后用postman直接调用 http://127.0.0.1:8086/auth/login 可以返回操作成功，但是在页面上点击登录还是不可以

**Comment by kkangert** [comment]
> 数据库内kspider_user为空，手动添加一条kangert和111111后用postman直接调用 http://127.0.0.1:8086/auth/login 可以返回操作成功，但是在页面上点击登录还是不可以

容器内的前端nginx配置有问题，今晚会修复问题

**Comment by xlsfs** [comment]
好的，我加了个
`
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
`
在外部写了个配置可以进去了

**Comment by kkangert** [comment]
> 好的，我加了个
> `
>     volumes:
>       - ./default.conf:/etc/nginx/conf.d/default.conf
> `
> 在外部写了个配置可以进去了

你也可以提个PR贡献❤
理论上需要copy这个配置到容器内，不需要配置卷

**Comment by kkangert** [comment]
此问题已修复 [相关提交](https://github.com/kkangert/kspider-ui/commit/3f4487c3d99e07b360c41f3dd323ba459acc0b4f)
